### ISSUE TITLE
Internal Error Bug Report [Automatically Created via App]

### ISSUE THREAD

**Issue by Zandiexoder** [xypwn/southpark-downloader-ui#11]
Version: 0.0.1 build 1
Error: GetEpisodeVTTSubtitles: get 'https://vs-tools.mtvnservices.com/caption/convert?mgid=mgid:file:gsp:alias:/mediabus/DTC/southParkStudiosUSen/359745/HDSS1204P2/HDSS1204P2_en-US_v2.dfxp.xml&accountName=intl.mtvi.com': HTTP error: 404 Not Found 
this error was shown for all S12 episodes

**Comment by xypwn** [comment]
Duplicate of #10
