### ISSUE TITLE
Internal Error Bug Report [Automatically Created via App]

### ISSUE THREAD

**Issue by LordRofl** [xypwn/southpark-downloader-ui#14]
Version: 0.0.1 build 1
Error: GetEpisodeParts: getHighlevelMedia: mediagen JSON: expected exactly 1 video rendition, but found 0

Moin, nices tool! Wenn ich es früher entdeckt hätte wäre ich bestimmt auch schon fertig :D 
Nun hänge ich bei Staffel 14 und nix geht mehr, leider auch nicht mit deinem downloader.

**Comment by xypwn** [comment]
Danke für das Kompliment und den Bugreport. Es gab wohl in letzter Zeit mehrere Leute mit ähnlichen Problemen. Ich schaue mir ganze  später heute an und schaue, ob man da was machen kann. Hab leider gerade nicht so viel Zeit.

Deine Region ist Deutschland, oder? Ist wichtig, weil die South Park web services in jedem Land etwas anders sind.

**Comment by LordRofl** [comment]
Genau, die ist Germany. Heute ist auch Feiertag, gönn dir ne Außzeit :)

**Comment by xypwn** [comment]
https://github.com/xypwn/southpark-downloader-ui/issues/10#issuecomment-2104035815

**Comment by xypwn** [comment]
Ich hab den Downloader für das neue System von Comedy Central angepasst (9c27d64306f1191ebc49bd74bc5c99c5cca5cad0). Es sollte jetzt alles wieder so wie vorher funktioneren.
Mach gerne ein neues Issue auf, falls es doch noch irgendwelche Probleme gibt.
