### ISSUE TITLE
Episodes are out of sync

### ISSUE THREAD

**Issue by M2rtinCH** [xypwn/southpark-downloader-ui#17]
The episodes are out of sync

**Comment by xypwn** [comment]
Please describe your issue in more detail and tell me what video player you're using.

**Comment by M2rtinCH** [comment]
I mean that the episodes once downloaded have the audio out of sync, out of
phase.
And I use VLC Media Player.

**Comment by xypwn** [comment]
I don't seem to be able to reproduce the issue. What episode did you have the problem on?

**Comment by M2rtinCH** [comment]
In several, for example: Buttersballs, Cartman Joins NAMBLA, etc.

**Comment by xypwn** [comment]
Hi, sorry for the late response. I can reproduce the issue on the episodes you've provided. I'll see to fixing it as soon as I find the time. Thanks for your bug report

**Comment by xypwn** [comment]
In my testing this fixed it, you can download the latest release. Please let me know if you still have any issues with sync.

**Comment by M2rtinCH** [comment]
Thanks, it worked. When you can, add episodes in other languages.
