### ISSUE TITLE
Error when download Season 8 Episode 10 subtitles

### ISSUE THREAD

**Issue by maximilian-hammerl** [xypwn/southpark-downloader-ui#19]
Version: 0.0.1 build 229
Error: GetEpisodeAsTS: download subtitle segment: get 'https://southpark.orchestrator.viacomcbs-tech.com/h/a/dG9wYXoxYDYwMTdmN2U2LWVjZmQtMTFlMC1hY2E2LTAwMjZiOTQxNGYzMGAxN2FjZmJlMDdjN2Y4Mzg0Y2MyMzMxOGZiNGZhOGZiMDg2M2UzZDk4YExmclBxQUg4WXVjSy1JeGdLZVh0bktrLThHNUhUYkFCdXlzM1Zud0FJOEE/segment-9-f9.vtt': HTTP error: 502 Bad Gateway
OS: windows amd64
Region: Germany
Description: I tried to download Season 8 Episode 10 in English from Germany.

- [X] I understand that this issue will be deleted if I forget to fill out any of the fields surrounded by brackets ("[ ]"), including the title. Place an "x" into the brackets at the beginning of this line to confirm.

(Created via app)

**Comment by xypwn** [comment]
Hi, sorry for the late response! I've been very busy over the last few months and didn't have the energy to put my head back into this project.

I'll be looking into what's going on in more detail soon, but just by looking at southpark.de, it seems this episode doesn't have any subtitles available at all. This means it could be some situation where the app expects subtitles to exist, but they actually don't. So it shouldn't be too difficult to fix.
