### ISSUE TITLE
Audio is quieter

### ISSUE THREAD

**Issue by Zweeflol** [xypwn/southpark-downloader-ui#20]
The audio is quieter when using the southpark-downloader-ui-windows-amd64.
![2024-08-15 18_30_40-South_Park_English_01_03_Best_Volcano](https://github.com/user-attachments/assets/2157d437-17a2-4238-a9b5-fcfdb65f78e9)
The above sound wave is from southpark-downloader-ui and the below sound wave is from yt-dlp (where I managed to download the episode before yt-dlp stopped working).

Not sure if its a southpark-downloader-ui or https://www.southparkstudios.com problem.

**Comment by xypwn** [comment]
I'll look at this a bit further, but will probably end up closing this as "won't fix".

Thanks for reporting this though :)
