### ISSUE TITLE
Certain episodes don't show inavailability correctly

### ISSUE THREAD

**Issue by Sk4lli** [xypwn/southpark-downloader-ui#23]
Version: 0.0.1 build 229
Error: GetEpisodeStream: invalid master URL: does not point to master.m3u8
OS: linux amd64
Region: Germany
Description: 
While initiating the download of Episode 10 Season 14 (German) i get the mentioned error.
i already restarted the app, rebooted the computer and waited several days .

btw downloading in English works.

- [x] I understand that this issue will be deleted if I forget to fill out any of the fields surrounded by brackets ("[ ]"), including the title. Place an "x" into the brackets at the beginning of this line to confirm.

(Created via app)

**Comment by xypwn** [comment]
When you go to https://www.southpark.de , it shows that the episodes aren't available, meaning there is no way for southpark-downloader-ui to source the video, so you won't be able to download it without a VPN / being in a region where it is available.

The app should, however, properly display the fact that episode isn't avilable, so I'll mark this as a bug. Thanks for reporting.
