### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by steseu** [xypwn/southpark-downloader-ui#26]
Version: 0.0.1 build 229
Error: GetEpisodeAsTS: download subtitle segment: get 'https://southpark.orchestrator.viacomcbs-tech.com/h/a/dG9wYXoxYDkwODdlMWFiLWU1YWEtNGIwNS04NTg1LTRlOWEwNzhmMTJlNmBhZTkyNDljZDQ0NTc2YjJmMTBkMjM2MDZlNzJjZDg0OWQyZmU1ZGE2YDBPZVE4V0xZTTRkaXFhV1Q4R05ycnpuZ3prc2tFT0cwdlZybm1mcG1SblU/segment-252-f9.vtt': Get "https://southpark.orchestrator.viacomcbs-tech.com/h/a/dG9wYXoxYDkwODdlMWFiLWU1YWEtNGIwNS04NTg1LTRlOWEwNzhmMTJlNmBhZTkyNDljZDQ0NTc2YjJmMTBkMjM2MDZlNzJjZDg0OWQyZmU1ZGE2YDBPZVE4V0xZTTRkaXFhV1Q4R05ycnpuZ3prc2tFT0cwdlZybm1mcG1SblU/segment-252-f9.vtt": read tcp 192.168.178.94:57870->146.75.123.2:443: wsarecv: An existing connection was forcibly closed by the remote host.
OS: windows amd64
Region: [YOUR REGION]
Description: [DESCRIBE THE ISSUE]

- [ ] I understand that this issue will be deleted if I forget to fill out any of the fields surrounded by brackets ("[ ]"), including the title. Place an "x" into the brackets at the beginning of this line to confirm.

(Created via app)

**Comment by xypwn** [comment]
To me, this looks like a network issue. What do you think I should fix about this?

**Comment by steseu** [comment]
Thank you for the feedback.
I wasn't sure, the downloader ran over night maybe a reconnecting router
was the cause.

xypwn ***@***.***> schrieb am Mi., 18. Dez. 2024, 12:52:

**Comment by xypwn** [comment]
I might address this with something like auto reconnect at some point, but I'm pretty busy right now, so this is just an idea for if I find the time :)
