### ISSUE TITLE
Galaxy S24

### ISSUE THREAD

**Issue by CrashKeks** [xypwn/southpark-downloader-ui#28]
Version: 0.0.1 build 233
Error: create temporary media directory: mkdir /Downloads: read-only file system
OS: android arm64
Region: [YOUR REGION]
Description: [DESCRIBE THE ISSUE]

- [ ] I understand that this issue will be deleted if I forget to fill out any of the fields surrounded by brackets ("[ ]"), including the title. Place an "x" into the brackets at the beginning of this line to confirm.

(Created via app)

**Comment by xypwn** [comment]
Unfortunately, Android isn't supported yet, as Fyne (the GUI/app framework) has yet to support for writing to a folder using Android's SAF
Sorry for the misleading info in the README and description, I updated those
