### ISSUE TITLE
Internal Error Bug Report [Automatically Created via App]

### ISSUE THREAD

**Issue by Paindeluxe** [xypwn/southpark-downloader-ui#6]
Version: 0.0.1 build 1
Error: GetEpisodeAsTS: downloadAndDecryptAES128Segment: get AES128 encrypted segment: get 'https://vimn-ns1.ts.mtvnservices.com/v1/gsp.alias/mediabus/2020/06/03/03/22/28/51fd387cd52847a5a96013e9fb592a50/1150607/0/seg_1920x1080_2705217_61_3121875261.ts': io.ReadAll: read tcp [2003:ef:df20:753c:3d80:4b5f:ac2c:3800]:52767->[2a04:4e42:6f::770]:443: wsarecv: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.

**Comment by xypwn** [comment]
This seems like a simple connection timeout, e.g. you lost connection.
Unless you get this error regularly, there's not reason to fix it.
I'll close the issue, but if you believe this is something that needs to be fixed, feel free to open a new issue, or comment on this one.
