### ISSUE TITLE
Produces garbage files when downloading from New Zealand

### ISSUE THREAD

**Issue by Zandiexoder** [xypwn/southpark-downloader-ui#8]
As the description says, is there something specific I need to do to get the video files by combining the MP4 or VTT file?

**Comment by xypwn** [comment]
No, it should produce a playable MP4.
Which episode(s) were you downloading and which country were you downloading them from?
Did the app show any errors?

**Comment by Zandiexoder** [comment]
Ah, I am downloading from New Zealand. Im guessing you are pulling the files off Comedy Central. The South Park episodes are not available in New Zealand. Im guessing this is what is causing the unwatchable files.

**Comment by Zandiexoder** [comment]
Also the app did not show any errors.

**Comment by xypwn** [comment]
Yes, it's pulling the data from the same official websites you can watch free streams on in some countries. If it's unavailable NZ, you'll need to use a VPN.
Nonetheless, it should show an error accordingly, so I'll keep this issue open until I fix it.

**Comment by Zandiexoder** [comment]
I'll close the issue.

**Comment by Zandiexoder** [comment]
Sorry I'll reopen

**Comment by xypwn** [comment]
Actually, I am using a VPN for NZ right now, and the online service seems to work.
I can also replicate your issue where garbage files are produced.

**Comment by xypwn** [comment]
I'll look into it when I find the time

**Comment by Zandiexoder** [comment]
I am using a custom DNS with Cloudflare and Google, could that make a difference?

**Comment by xypwn** [comment]
Probably not, since I have the same issue when using a VPN for New Zealand specifically. Other regions work just fine, and the website works for me, even with NZ VPN.

**Comment by Zandiexoder** [comment]
Here the link to the garbage files if you think they would be useful: [](https://drive.google.com/drive/folders/1VKe4j6rzlyMOkHM7Osp6zMAX947FycZU?usp=drive_link
)

**Comment by Zandiexoder** [comment]
When using a US Vpn downloading one of the limited episodes available provides a functioning video file.

**Comment by xypwn** [comment]
Hey, sorry for the very late response. I've had a lot of other stuff going on recently.
It seems Comedy Central changed their whole video delivery system, and I had to change the downloader accordingly. With these major changes it seems your NZ specific problem has been resolved implicitly (according to my VPN testing).
Feel free to open a new issue if you're still facing any problems.
